namespace: default
env: dev
k8s_1dot8_or_above: true
has_static_volumes: true
services:
  expose_node_port: true
docker:
  registry: docker.io
  namespace: ffdl
  image_prefix: ffdl-
  pullPolicy: IfNotPresent
  imagePullSecret: regcred
trainingdata:
  image_name: training-data-service
  version: v0.1.1
  port: 0
  replicas: 1
  cpus: 50m
  memory: 64Mi
elasticsearch:
  address: http://elasticsearch:9200
  username: test
  password: test
  scheme: http
log:
  level: INFO
